server:
    port: 8090

file:
    upload-dir: /Users/user/desktop/web

spring:
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 250MB
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: 1234qw
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                enable_lazy_load_no_trans: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: library@lib.com
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true


jwt:
    access:
        key: tHaX54Hwk^YMzKd@e@p7#70OZn0#D98BK8C1%T&hBnrzgqK28o
        expiration-time: 72000000
    refresh:
        key: tHaX54Hwk^YdfdsMzK-d@e@&p7#%70OZ()BK8C1%T&hBnrzgqK287
        expiration-time: 604800000