POST http://localhost:8090/api/role/set-role/1/fb51613b-f70a-4883-a5f4-7923ae4b1342
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtdWhhbW1hZGF6aXouZXJnLjEyMjlAZ21haWwuY29tIiwiaWF0IjoxNjY5OTA1NTIwLCJleHAiOjE2Njk5Nzc1MjB9.UKtsG8hwa1sCYnJm_GDYzLAZgCNWPvMeGSRPJHtf8SRN86KJl0fHnzRGPaIRtDsXNQjtKQMU41_S5lGJw0GqNw
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE2Njk5MDU2NzYsImV4cCI6MTY2OTk3NzY3Nn0.ZbLdY-yeIN4gfBXvhXC42RFY7I7wI7l9-KiUVyJE5Tsg4g3xofOChF7YPcJgsNeJRlfyw_iKBeWn9k4kvJJt0A
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlckFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY2OTkwODY5MywiZXhwIjoxNjY5OTgwNjkzfQ.M7EbWpe3xfjifEnuZmFNagJ7ybdeYYGBKXZyM2jyoy43fKF4RqfYobYSDCgf7ZGIrd7uBt8orU8dicDoz93FMA

###
POST http://localhost:8090/api/book/new
Content-Type: multipart/form-data

{

}


###
GET http://localhost:8090/api/book/download/2