
POST http://localhost:8090/api/auth/sign-in
Content-Type: application/json

{
  "email": "superAdmin@admin.com",
  "password": "123"
}

###
POST http://localhost:8090/api/auth/sign-up
Content-Type: application/json

{
  "email": "muhammadaziz.erg.1229@gmail.com",
  "password": "123"
}


